[2024-06-22T07:47:54.871+0000] {processor.py:161} INFO - Started process (PID=2107) to work on /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:47:54.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_operator_dag.py for tasks to queue
[2024-06-22T07:47:54.872+0000] {logging_mixin.py:188} INFO - [2024-06-22T07:47:54.872+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:47:54.881+0000] {logging_mixin.py:188} INFO - [2024-06-22T07:47:54.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_operator_dag.py", line 7, in <module>
    'retry_delay': timedelta(minutes=2)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-06-22T07:47:54.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:47:54.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_operator_dag.py took 0.037 seconds
[2024-06-22T07:48:15.108+0000] {processor.py:161} INFO - Started process (PID=2109) to work on /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:48:15.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_operator_dag.py for tasks to queue
[2024-06-22T07:48:15.110+0000] {logging_mixin.py:188} INFO - [2024-06-22T07:48:15.110+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:48:15.118+0000] {logging_mixin.py:188} INFO - [2024-06-22T07:48:15.116+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_operator_dag.py", line 12, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-06-22T07:48:15.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:48:15.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_operator_dag.py took 0.034 seconds
[2024-06-22T07:48:16.123+0000] {processor.py:161} INFO - Started process (PID=2110) to work on /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:48:16.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/python_operator_dag.py for tasks to queue
[2024-06-22T07:48:16.124+0000] {logging_mixin.py:188} INFO - [2024-06-22T07:48:16.124+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:48:16.131+0000] {logging_mixin.py:188} INFO - [2024-06-22T07:48:16.130+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/python_operator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/python_operator_dag.py", line 12, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2024-06-22T07:48:16.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/python_operator_dag.py
[2024-06-22T07:48:16.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/python_operator_dag.py took 0.033 seconds
