[2024-06-22T07:41:31.195+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T07:41:31.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_v2.first_task manual__2024-06-22T07:41:30.190033+00:00 [queued]>
[2024-06-22T07:41:31.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_v2.first_task manual__2024-06-22T07:41:30.190033+00:00 [queued]>
[2024-06-22T07:41:31.209+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-22T07:41:31.215+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2024-06-22 07:41:30.190033+00:00
[2024-06-22T07:41:31.217+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1999) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-22T07:41:31.218+0000] {standard_task_runner.py:63} INFO - Started process 2000 to run task
[2024-06-22T07:41:31.218+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v2', 'first_task', 'manual__2024-06-22T07:41:30.190033+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpae8i92bo']
[2024-06-22T07:41:31.219+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask first_task
[2024-06-22T07:41:31.238+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag_v2.first_task manual__2024-06-22T07:41:30.190033+00:00 [running]> on host 65f8df8d6172
[2024-06-22T07:41:31.273+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gnosia93' AIRFLOW_CTX_DAG_ID='first_dag_v2' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T07:41:30.190033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T07:41:30.190033+00:00'
[2024-06-22T07:41:31.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T07:41:31.279+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-22T07:41:31.280+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world. gnosia93']
[2024-06-22T07:41:31.284+0000] {subprocess.py:86} INFO - Output:
[2024-06-22T07:41:31.284+0000] {subprocess.py:93} INFO - hello world. gnosia93
[2024-06-22T07:41:31.285+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-22T07:41:31.285+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T07:41:31.297+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag_v2, task_id=first_task, run_id=manual__2024-06-22T07:41:30.190033+00:00, execution_date=20240622T074130, start_date=20240622T074131, end_date=20240622T074131
[2024-06-22T07:41:31.320+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-22T07:41:31.330+0000] {taskinstance.py:3503} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-06-22T07:41:31.331+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
